##!
# The server configuration is set by a `YAML <http://yaml.org/>`_ file, ``config.yml``.
# A number of parameters are set here, and read by the :mod:`WorkflowWebTools.serverconfig`:
#
# - The webmaster name and email determines who the registration emails are sent from.
# - The host name and port tell where to serve the cherrypy application if using the CherryPy server.
# - The data locations are split up into
#
#   - Historic information
#   - Location to fetch the current errors
#   - Location to fetch the current errors' explanations
#   - If any of these files are behind Shibboleth,
#     cookie_file, cookie_pem, and cookie_key should be listed under data too.
#     These keys are used as kwargs for :py:func:`CMSToolBox.get_json`
#
# - Valid registration email domains and specific whitelisted emails
# - Actions stores the number of days to check the submission history for actions requested
# - Clustering parameters 
#
# See :mod:`WorkflowWebTools.clusterworkflows` for more details on the clustering parameters.
##!

webmaster:
  name: Daniel Abercrombie  # Will show up in certain emails
  email: dabercro@mit.edu   # cc'd on those emails
host:
  name: 127.0.0.1           # Where we are hosting the service
  port: 8080                # Which port the service shows up
data:
  # All of the errors to cluster with and link to actions
  # Use runserver/update_history.py to keep this up to date
  workflow_history: test/history.db
  # The location of where to get the workflows with errors      
  # See errorutils module for how this file is read:
  # http://cms-comp-ops-tools.readthedocs.io/en/latest/workflowwebtools.html#module-WorkflowWebTools.errorutils
  all_errors: test/errors.json
  # Not actually used anymore. Should probably be removed soon
  explain_errors: test/explained.json
  # Used to locate certificates for cern-get-sso-cookie
  # See CMSToolBox.webtools.get_cookie_header for details:
  # http://cms-comp-ops-tools.readthedocs.io/en/latest/toolbox.html#CMSToolBox.webtools.get_cookie_header
#  cookie_file: optional
#  cookie_pem: optional
#  cookie_key: optional
# These are emails that are allowed be used to sign up for the service
valid_emails:
  # Either domains must match
  domains:
    - cern.ch
#    - fnal.gov    # Maybe good to add these guys too
  # Or we have explicit emails to whitelist, if people prefer
  whitelist:
    - dabercro@mit.edu
actions:
  # Used to highlight workflows that have been acted on in this many days
  submithistory: 2
  # The key that must match when reported with report_action.py
  key: testkey
  # These are the parameters for connecting to the mongodb instance that holds actions
  database: test_workflowwebtools
  # Optional URI connection string
#  uri: mongodb://user:password@host[:port]/database?ssl=true
cluster:
  # Clustering parameters for k-means
  # See WorkflowWebTools.clusterworkflows.get_clusterer :
  # http://cms-comp-ops-tools.readthedocs.io/en/latest/_modules/WorkflowWebTools/clusterworkflows.html#get_clusterer
  n_clusters: 2
  n_init: 30
  # Explanation attempted here:
  # http://cms-comp-ops-tools.readthedocs.io/en/latest/workflowwebtools.html#module-WorkflowWebTools.clusterworkflows
  sitename:
    distance: 1.0
    width: 0.2
    midpoint: 50
  errorcode:
    distance: 2.0
    width: 0.4
    midpoint: 50
# Refresh cached jsons in WorkflowWebTools.workflowinfo jsons
# This is maximum age in seconds
cache_refresh:
  errors: 345600
workspace: '.'
